package com.googlecode.reaxion.game.audio;

public enum SoundEffectType {
	ATTACK_LIGHTNING_CLOUD, ATTACK_LIGHTNING_STORM, 
	ATTACK_FIREBALL, 
	ATTACK_BLACK_HOLE, 
	ATTACK_BUBBLE_SPAWN, ATTACK_BUBBLE_POP,
	ATTACK_CARD_THROW;
}
